import { Head } from '@inertiajs/react';
import Heading from '@/components/heading';
import { Badge } from '@/components/ui/badge';
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from '@/components/ui/table';
import type { Paginated } from './types';

type FinanceEntryRow = {
    id: number;
    entry_date: string | null;
    shift_id: number | null;
    type: string;
    direction: string;
    payment_method: string | null;
    amount: number;
    created_by: string | null;
    notes: string | null;
    created_at: string | null;
};

const currency = new Intl.NumberFormat('id-ID', {
    style: 'currency',
    currency: 'IDR',
    maximumFractionDigits: 0,
});

export default function PosFinance({
    entries,
}: {
    entries: Paginated<FinanceEntryRow>;
}) {
    return (
        <>
            <Head title="POS Finance" />

            <div className="flex h-full flex-1 flex-col gap-6 overflow-x-auto p-4">
                <Heading
                    title="POS Finance"
                    description="Ledger entries generated by POS payments and operational finance events."
                />

                <div className="overflow-hidden rounded-lg border">
                    <Table>
                        <TableHeader>
                            <TableRow>
                                <TableHead>Date</TableHead>
                                <TableHead>Type</TableHead>
                                <TableHead>Source</TableHead>
                                <TableHead>Method</TableHead>
                                <TableHead className="text-right">
                                    Amount
                                </TableHead>
                            </TableRow>
                        </TableHeader>
                        <TableBody>
                            {entries.data.length ? (
                                entries.data.map((entry) => (
                                    <TableRow key={entry.id}>
                                        <TableCell>
                                            <div>
                                                {entry.entry_date ?? '-'}
                                            </div>
                                            <div className="text-xs text-muted-foreground">
                                                {entry.created_at
                                                    ? new Date(
                                                          entry.created_at,
                                                      ).toLocaleString('id-ID')
                                                    : '-'}
                                            </div>
                                        </TableCell>
                                        <TableCell>
                                            <div className="font-medium">
                                                {entry.type}
                                            </div>
                                            <Badge variant="secondary">
                                                {entry.direction}
                                            </Badge>
                                        </TableCell>
                                        <TableCell>
                                            <div>
                                                Shift #{entry.shift_id ?? '-'}
                                            </div>
                                            <div className="text-xs text-muted-foreground">
                                                By {entry.created_by ?? '-'}
                                            </div>
                                        </TableCell>
                                        <TableCell>
                                            <Badge variant="outline">
                                                {entry.payment_method ?? '-'}
                                            </Badge>
                                        </TableCell>
                                        <TableCell className="text-right font-semibold">
                                            {currency.format(entry.amount)}
                                        </TableCell>
                                    </TableRow>
                                ))
                            ) : (
                                <TableRow>
                                    <TableCell
                                        colSpan={5}
                                        className="h-32 text-center text-muted-foreground"
                                    >
                                        No finance entries yet.
                                    </TableCell>
                                </TableRow>
                            )}
                        </TableBody>
                    </Table>
                </div>
            </div>
        </>
    );
}

PosFinance.layout = {
    breadcrumbs: [
        {
            title: 'POS Finance',
            href: '/pos/finance',
        },
    ],
};
